export const configuration={
    header:{
        heading:'A FREE & USEFUL LATEST TECH UPDATE PORTAL',
        headingText:'InfoTip is a free source portal where you can find and know more about latest technologies. It is very helpful for your daily life routine, enjoy the reading!',
        buttonText:'JOIN US',
        buttonLink:'\home'
    },
    intro:{
        introHead: 'Here we are to help you to know more about the tech updates.',
        headPara: 'Join us to keep yourself udpated.',
        features: [
            {icon: 'html5', title:'HTML5', paragraph:'HTML5 is the latest evolution of the standard that defines HTML. The term represents two different concepts. It is a new version of the language HTML, with new elements, attributes, and behaviors, and a larger set of technologies that allows the building of more diverse and powerful Web sites and applications. This set is sometimes called HTML5 & friends and often shortened to just HTML5.<br/><br/>Designed to be usable by all Open Web developers, this reference page links to numerous resources about HTML5 technologies, classified into several groups based on their function.<br/><br/><ul> <li><em>Semantics</em>: allowing you to describe more precisely what your content is.</li> <li><em>Connectivity</em>: allowing you to communicatewith the server in new and innovative ways.</li> <li><em>Offline and storage</em>: allowing webpages to store data on the client-side locally and operate offline more efficiently.</li> <li><em>Multimedia</em>: making video and audio first-class citizens in the Open Web.</li> <li><em>2D/3D graphics&nbsp;and effects</em>: allowing a much more diverse range of presentation options.</li> <li><em>Performance and integration</em>: providing greater speed optimization and better usage of computer hardware.</li> <li><em>Device access</em>: allowing for the usage of various input and output devices.</li> <li><em>Styling</em>: letting authors write more sophisticated themes.</li></ul>'},
            {icon: 'google', title:'Algorithm Updates', paragraph:'Google has a long history of famous algorithm updates, search index changes and refreshes. <br/>Like <ul><li><a href="/hummingbird-google" title=" Google Hummingbird search platform update for semantic search relevancy">Google Hummingbird</a></li><li><a href="/google-mobile-friendly-update" title="Google&#39;s Mobile Friendly Update">Google Mobile Friendly Update</a></li><li><a href="/google-panda-update" title=" Google Panda update targets spammy sites with thin content">Google Panda Update</a></li><li><a href="/google-penguin-update" title=" Google Penguin Update targets link spam">Google Penguin Update</a></li><li><a href="http://searchengineland.comgoogle-pigeon-update" title="Google Pigeon Update affects local search results">Google Pigeon Update</a></li><li><a href="http://searchengineland.comgoogle-payday-update" title="Google Payday Update affects SERPs for Payday loans and other spammy queries">Google Payday Update</a></li><li><a href="http://searchengineland.comgoogle-pirate-update " title="Google Pirate Update">Google Pirate Update</a></li><li><a href="http://searchengineland.comemd-update" title="Google EMD - Exact Match Domain Update">Google EMD (Exact Match Domain) Update</a></li><li><a href="http://searchengineland.comgoogle-top-heavy-update " title="Google Top Heavy Update affects pages with too many ads above the fold ">Google Top Heavy Update</a></li></ul>'}
            //{icon: 'language-python-alt', title:'python', paragraph:'Id porro tritani recusabo usu, eum intellegam consequuntur et. Fugit debet ea sit, an pro nemore vivendum'},
            //{icon: 'rocket', title:'Parallax Effect', paragraph:'Id porro tritani recusabo usu, eum intellegam consequuntur et. Fugit debet ea sit, an pro nemore vivendum'},
        ]
    }
}